### ISSUE TITLE
Realtime Data scrapying [SOLVED]

### ISSUE THREAD

**Issue by badcannon** [scrapinghub/scrapyrt#104]
Hey there ,

I was really wondering how to get the splash requests working with the scrapyrt . I tried a bunch ,but couldn't figure out much , I did look into the only thread which is similar to my question , but couldn't get it to work , here is my code : 
```
import scrapy
import requests
import json
from scrapy_splash import SplashRequest 
 
class MangaChapters(scrapy.Spider):
    name = "mangaChapters"
     
    def start_requests(self):
        # tell ScrapyRT to render request with Splash
        yield SplashRequest(url, self.parse,
                args={'wait':5},
                endpoint= 'render.html'
            )
        

    def parse(self,response):
        chapters = response.css('.img').xpath('@src').extract()
        yield {
            'chapters' : chapters
        }
```

and can i pass the url from the request api in scrapyrt

**Comment by BuSSioR** [comment]
Hi! Please provide more details, do you get any errors? Did you run splash and provided its address in settings?

**Comment by badcannon** [comment]
Hey thanks for the reply , I got it working , I went through the documentation again and got it to work !
