### ISSUE TITLE
Putting scrapyrt into production

### ISSUE THREAD

**Issue by thepyguy** [scrapinghub/scrapyrt#108]
I'm going to be putting scrapyrt into production on a project here soon. I am using it with Crawlera proxies.

Users on a website will be hitting the API from a form on the website. I was wondering how the scheduling of spiders works and if there's a way to limit individual spider concurrency and also having a maximum project concurrency? Should I over ride CONCURRENT_REQUESTS  on the spider with custom settings and would this limit each instance or the spider as a whole I'm assuming it would limit each instance? If multiple requests are made to the API simultaneously will they all go at once or will they be scheduled to run FIFO or ?

Any information you guys can give me on this would be great so I can get a handle on how many users it can handle at once.  Or if it can't work this way out of the box do I need to over ride the runner or ?

My desired outcome would be to limit each spider to 10 concurrent requests and to have the spiders run concurrently until maximum concurrency is reached and then schedule any subsequent requests to run when the previous ones finish.

Also, is there a way I can secure it with an API key so the public can't access it?

Thanks

**Comment by pawelmhm** [comment]
Hello

> if there's a way to limit individual spider concurrency 

For spider concurrency: yes, just like you limit with CONCURRENT_REQUESTS [Scrapy spider concurrency](https://docs.scrapy.org/en/latest/topics/settings.html#concurrent-requests)

> and also having a maximum project concurrency? 
if you mean max concurrency across spiders, this is not possible. Concurrency settings in Scrapy are applied per spider. There are no settings in ScrapyRT to allow you to set concurrency for group of spiders, e.g. you cannot set concurrency of 100 and apply it to 10 spiders, make each one limit number of concurrent requests to 10

>  Should I over ride CONCURRENT_REQUESTS on the spider with custom settings

This is your decision, depending on your use case. CONCURRENT_REQUESTS are there to protect websites from excessive traffic, it does limit amount of RAM memory or CPUsed by your application if you set it to lower than default, so yeah having this settings might affect your ScrapyRT application but it all depends on your use case, hardware used etc.

> If multiple requests are made to the API simultaneously will they all go at once or will they be scheduled to run FIFO or ?

All spiders are scheduled concurrently, there is no limit on amount of spiders that are running at the same time. So if you make 100 requests on 10:00 scheduling 100 spiders, they will all launch on 10:00, another requests with 200 spiders on 10:01 - 200 spiders launched on 10:01. 

In my experience I've seen several hundreds of spiders running at the same time and it went fine. I would start without limits and see how it goes, if you see some problem you can think about adding some rate limits. 

> Also, is there a way I can secure it with an API key so the public can't access it?

No, we don't have this feature, it is useful things to have and we could add it at some point in time. 

You could add it either on application level or simply put ScrapyRT behind nginx and configure authentication in nginx https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10

**Comment by thepyguy** [comment]
So even if CONCURRENT_REQUESTS is set in my settings.py it will apply to each spider and not the over all project? The only reason I am concerned is staying within limits of the proxy plan. I think you are right just let it run, gather some data and adjust as necessary either concurrent requests and/or proxy plan. 

As far as authentication I agree I think I will either run it on the localhost or just whitelist the IPs that I wish to have acces via firewall should I have to deploy remotely.

**Comment by thepyguy** [comment]
The only reason I am wanting to rate limit is because I am using a Crawlera plan so I can't put CONCURRENT_REQUESTS over that. So I was hoping that I could say limit each request to 10 concurrency since each request does not need the full 50. If I were to over-ride the setting on the spider with custom_settings would that allow this behavior? I am just trying to get a handle on how many users a full load is and if I can limit each calls concurrency to allow more users at a time.

What is the behavior with scrapyrt could I set global concurrent_requests in settings.py to 50 and then over ride that in each spider @ 10 so I could effectively support 5 concurrent users?

**Comment by pawelmhm** [comment]
> So even if CONCURRENT_REQUESTS is set in my settings.py it will apply to each spider and not the over all project?

correct
> My understanding is CONCURRENT_REQUESTS is a global limit.
[This is limit set by Scrapy downloader](https://docs.scrapy.org/en/latest/topics/settings.html#concurrent-requests) and each spider has separate downloader. There is no common downloader in ScrapyRT, all spiders are created with its own downloader, set of pipelines etc

>  I am using a Crawlera plan so I can't put CONCURRENT_REQUESTS over that

You can send as many requests as you can to crawlera as you wish, and it will apply its own limits. You don't have to apply limits your side, you can just let crawlera rate limit you. Drawback is you may see slower performance if you exceed limits imposed by crawlera (requests from crawlera will return after longer time because they will have to wait in queue in crawlera). Disclaimer: I'm not crawlera support and I don't know details of different plans.

> What is the behavior with scrapyrt could I set global concurrent_requests in settings.py to 50 and then over ride that in each spider @ 10 so I could effectively support 5 concurrent users?

No, that won't work. This way your application still can schedule 100 spiders with each spider making 10 concurrent requests.

**Comment by thepyguy** [comment]
@pawelmhm thanks for clearing that up for me. This is closed but I am going to have to open another issue I think if I can't find in docs.
