### ISSUE TITLE
Can scrapyrt be made to work with scrapy's start_requests array?

### ISSUE THREAD

**Issue by doverradio** [scrapinghub/scrapyrt#128]
Is this possible?  I have not seen this is documentation and found some mentions of it within the codebase but I have been unable to do it.

**Comment by pawelmhm** [comment]
Yes, have you tried start_requests=True parameter, by default start_requests are not enabled, but if you specify some parameter it will be, see information here: https://scrapyrt.readthedocs.io/en/latest/api.html#scrapyrt-http-api
