### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by Ed1123** [scrapinghub/scrapyrt#145]
As of January 2023, is this still maintained or is it safe to use in its current state?

**Comment by avlm** [comment]
I'd like to know too..

**Comment by pawelmhm** [comment]
There are no new features planned, but looks like we may need to have a new release to keep project stable and running because of https://github.com/scrapinghub/scrapyrt/issues/148 I'm more than happy to review any pull requests if anyone has any features or bug fixes they want to add.
