### ISSUE TITLE
can scrapyrt be used to schedule scrapes?

### ISSUE THREAD

**Issue by doverradio** [scrapinghub/scrapyrt#146]
I am using scrapyrt extensively by just sending requests from another server where that other server has been using crontab.  

However, I began wondering if I could just set scrapyrt to a schedule instead of having to fire all these requests.

This github repo states "It starts HTTP server allowing you to schedule spiders and get spider output in JSON."

However, that's the only mention of "schedule spiders".  

Is there a way?

**Comment by ankitjavalkar** [comment]
`scrapyd` would better suit your use case. See https://scrapyd.readthedocs.io/en/latest/overview.html#scheduling-a-spider-run
