### ISSUE TITLE
exceptions.AttributeError: 'ScrapyrtCrawlerProcess' object has no attrib ute 'crawl'

### ISSUE THREAD

**Issue by println2** [scrapinghub/scrapyrt#17]
when i try to run scrapy using scrapyrt i am getting this error please help me
![error](https://cloud.githubusercontent.com/assets/11938531/7132128/15ec1cc4-e2a4-11e4-97d0-92ae5dad4598.png)

**Comment by chekunkov** [comment]
Hello @println2, can you tell me what version of Scrapy is installed in your environment?

**Comment by println2** [comment]
scrapy 0.24.4 @chekunkov

**Comment by chekunkov** [comment]
@println2 Unfortunately ScrapyRT doesn't support latest stable version of Scrapy from PyPI and relies a lot on features available in master branch. Please check recommended Scrapy version in [requirements.txt](https://github.com/scrapinghub/scrapyrt/blob/master/requirements.txt#L2). We don't have plans to add support for Scrapy 0.24 to ScrapyRT as we are expecting new stable version of Scrapy to be available soon.
