### ISSUE TITLE
Return custom HTTP code from spider

### ISSUE THREAD

**Issue by busla** [scrapinghub/scrapyrt#22]
Is there any way I can return back to scrapyrt from my spider with a custom HTTP code and message?

Let´s say I´m trying to login but have the wrong user and password. I check for the error text in xpath and return a HTTP 401 with a custom message.

Thanks for a lovely library.

Cheers

**Comment by chekunkov** [comment]
You can do that by raising [CloseSpider](http://doc.scrapy.org/en/1.0/topics/exceptions.html#closespider) with custom reason in your spider, extending `scrapyrt.core.CrawlManager.return_items` to detect that and raise `twisted.web.error.Error` with appropriate http code and message, like this:

```python
from twisted.web.error import Error
from scrapyrt.core import CrawlManager as ScrapyrtCrawlManager


class CrawlManager(ScrapyrtCrawlManager):

        def return_items(self, result):
            results = super(CrawlManager, self).return_items(result)
            if results['stats']['finish_reason'] == 'not authorised!':  # custom reason
                raise Error(401, 'Oh!')
            return results
```

Add path to this `CrawlManager` in [CRAWL_MANAGER](https://github.com/scrapinghub/scrapyrt#crawl-manager) setting, run your spider and you should get this:

```
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Origin: *
Content-Length: 51
Content-Type: application/json
Date: Wed, 19 Aug 2015 18:42:09 GMT
Server: TwistedWeb/15.2.1

{
    "code": 401,
    "message": "Oh!",
    "status": "error"
}
```

Talking about your usecase - it sounds like you are going to misuse HTTP code 401. 401 should be returned if your ScrapyRT server uses some authentication mechanism and you want to tell user that he/she should provide correct credentials before using ScrapyRT server. If you want to tell user that he/she passed incorrect spider arguments and therefore crawl fails - I would recommend you to return HTTP 400 with custom error message.

**Comment by busla** [comment]
Great stuff, thanks for helping out.

After reading up on 400, it seems the way to go. The host I´m trying to login into doesn´t return 401 so I thought I would do it instead :-)
