### ISSUE TITLE
Port binding error on heroku boot

### ISSUE THREAD

**Issue by adipasquale** [scrapinghub/scrapyrt#25]
Hi,

I'm trying to release a scrapyrt server on heroku. I'm *almost* there, but I still have an issue on bootup : heroku doesn't detect the port as properly 'bound' to .. 

my Procfile looks like this :
`web: scrapyrt -p $PORT`

and the logs on heroku bootup look like this : 
```
2016-01-24T15:52:37.903625+00:00 heroku[web.1]: Starting process with command `scrapyrt -p 21555`
2016-01-24T15:52:40.549269+00:00 app[web.1]: 2016-01-24 15:52:40+0000 [-] Log opened.
2016-01-24T15:52:40.605826+00:00 app[web.1]: 2016-01-24 15:52:40+0000 [-] Site starting on 21555
2016-01-24T15:52:40.606006+00:00 app[web.1]: 2016-01-24 15:52:40+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f26e9e8b950>
2016-01-24T15:53:38.378592+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

I've checked and everything seems to be running fine, when running it from a `heroku run bash` one off instance, and starting a `scrapyrt` process in the background, I can query it via `curl localhost:8090/crawl.json` without a problem. 
I also checked with a simple Twisted server by replacing my Procfile with `twistd --nodaemon web -p $PORT` and it worked fine. 

I'm not a big Twisted expert nor HTTP/TCP protocols, but I guess something is not done like a classic web server. I've seen that you use a `TCPServer` class, maybe there's something I'm missing ? There's a [heroku doc page](https://devcenter.heroku.com/articles/ruppells-sockets) for a plugin that allows routing TCP sockets to app's dynos, but I don't think this applies. Also, I couldn't find any precise info on how heroku checks for port binding .. 

Maybe you can point me in the right direction if you have some insight and save me some debugging time :) 
I'd also be happy to write some doc on how to deploy to heroku afterwards, as I already ran into a few more caveats. 

I :heart: scrapy !

**Comment by sibiryakov** [comment]
Hey @adipasquale, please check what network interfaces are available in heroku container. By default scrapyrt binds on localhost, which isn't necessary routed outside of container.

**Comment by chekunkov** [comment]
@adipasquale try

```
scrapyrt -i 0.0.0.0 -p $PORT 
```

**Comment by adipasquale** [comment]
it works great ! thank you
do you think it'd be interesting to add a "deploy to heroku" section to the readme ? or a wiki page ?
FYI, the other *tricky* steps were to use a `bin/post_compile` script to download and install `scrapyrt` from the source and to add `cffi==1.5.0` to the requirements.txt (the pip install of scrapy fails otherwise)

**Comment by redapple** [comment]
@adipasquale , if you could start a Wiki page for this, that would be great! Thanks.
We can see where to put it afterwards (README may need to become docs, IMO)

**Comment by sibiryakov** [comment]
I would expect the same issue with binding in Docker containers too.

**Comment by alafanechere** [comment]
@sibiryakov yes I encountered the same issue working with Docker. Thanks for your answers it solved my problem.

**Comment by ecalaj** [comment]
this still fails
