### ISSUE TITLE
Default Log Format Incompatible With Windows

### ISSUE THREAD

**Issue by zolrath** [scrapinghub/scrapyrt#43]
The [default log file](https://github.com/scrapinghub/scrapyrt/blob/master/scrapyrt/core.py#L167) of `datetime.datetime.now().isoformat() + '.log'` does not work on Windows as `:` is an unsupported character in filenames. It'd be nice to replace them with another character!

**Comment by pawelmhm** [comment]
glad this is only thing that fails on windows @zolrath ! We haven't tested this on windows. If you'd like to fix this PR-s are welcome.

**Comment by pawelmhm** [comment]
ah ok I see there is PR already #44

**Comment by pawelmhm** [comment]
fixed via #44
