### ISSUE TITLE
Asynchronous running

### ISSUE THREAD

**Issue by lboynton** [scrapinghub/scrapyrt#51]
(This should have a question label, however I can't seem to add it myself)

Hello, I've been taking a look at this project to handle the running of multiple, potentially long running crawlers at once. Currently it seems if you have a long running crawler, the API will simply wait until is has finished before returning the response.

Is it possible to start a crawler in the background and then check the status/get the crawler result via the API?

**Comment by chekunkov** [comment]
Hi @lboynton! ScrapyRT runs crawlers synchronously by design. If you need to run jobs asynchronously - use https://scrapyd.readthedocs.io/en/stable/. Or sign up to https://scrapinghub.com/scrapy-cloud/ and run your crawlers there.

**Comment by lboynton** [comment]
OK, thanks @chekunkov !
