### ISSUE TITLE
How can i use scrapyrt on production on my own server?

### ISSUE THREAD

**Issue by mangeshsn** [scrapinghub/scrapyrt#63]
i tried to start scrapyrt using terminal but after some time it times out.
is there any way i can run scrapyrt on production?
Thanks.

**Comment by pawelmhm** [comment]
hey @mangeshsn  we need to add deployment section to wiki there is issue for this #26 can you run docker on your server? if yes you can just pull docker image and run it

**Comment by mangeshsn** [comment]
okay Thanks, @pawelmhm .
