### ISSUE TITLE
How to connect to scrapyrt from outside?

### ISSUE THREAD

**Issue by Miando** [scrapinghub/scrapyrt#67]
I deployed my code to digitalocean server by cant run crawl via GET request from outside. From server localy, works fine

**Comment by Miando** [comment]
Ok, I finded in --help option -i. May be it option need to add to docs?

**Comment by JimmyNi** [comment]
Also got the problem, anyone help?

**Comment by aleroot** [comment]
You need to configure Docker networking, expose the port you want to access from outside.

Take a look at the [Docker networking documentation](https://docs.docker.com/engine/userguide/networking/) for more information...

**Comment by llermaly** [comment]
@JimmyNi  

Solved it adding the "-i" argument with my VPS IP

**Comment by pawelmhm** [comment]
This is more about setting up your server, not really about ScrapyRT so closing.
