### ISSUE TITLE
all items are replaced by last crawled item.

### ISSUE THREAD

**Issue by HassanQamar07** [scrapinghub/scrapyrt#69]
In response items, all the items are replaced by last crawled item.  While debugging `core.py`, it seems like every item in `self.items` is a shallow copy which is causing the issue. A *deepcopy* of every item can fix the issue.

https://github.com/scrapinghub/scrapyrt/blob/master/scrapyrt/core.py#L242

**Comment by pawelmhm** [comment]
hey @HassanQamar07 

can you create some sample that will allow to reproduce this problem? Using for example https://github.com/scrapy/quotesbot Which python version, scrapy version etc. are you using?

**Comment by HassanQamar07** [comment]
@pawelmhm Sorry, I found the issue, it was in my code. I was passing item to itemloader and returning multiple item on single response.
