### ISSUE TITLE
dockerfile python3 support

### ISSUE THREAD

**Issue by shadiakiki1986** [scrapinghub/scrapyrt#74]
Hello. Awesome app! :1st_place_medal: The dockerfile still uses python2 though. I'd like to submit a PR for a new file for python3 support. You can maintain support for both with separate tags, e.g. `scrapinghub/scrapyrt:python2` and `scrapinghub/scrapyrt:python3`. Thoughts?

**Comment by pawelmhm** [comment]
@shadiakiki1986 sorry for late response. I think we can make docker use Python 3 by default. No point using Python 2 in 2019. You can do it yourself or I can do it if you're busy with other things.

**Comment by shadiakiki1986** [comment]
TBH I'd rather you did it. You might also want to upgrade from the ubuntu:14.04 base image to something more recent.
