### ISSUE TITLE
Parallel crawling of different URLS doesn't work

### ISSUE THREAD

**Issue by olheimer** [scrapinghub/scrapyrt#80]
Hi,

I'm calling the scrapyRT interface with different urls to be crawled "in parallel". The result is always the same. Only one returns the others never return.

http://myserver/crawl.json?spider_name=mySpider&url=TheURLToCrawl
The settings are more or less default.

If I crawl each url after the other all respond correctly.

Is this a known issue? How would parallel crawling work with scrapyRT?

Thanks in advance!

**Comment by 111qqz** [comment]
Same problem here

**Comment by debasissaha1982** [comment]
Sam problem please help
