### ISSUE TITLE
Bug when install scrapyrt

### ISSUE THREAD

**Issue by wwwangzhch** [scrapinghub/scrapyrt#82]
Hi,
When i use command `pip install scrapyrt` it shows i succesfully installed scrapyrt-0.10, but when i run `scrapyrt` in command line, it shows "RuntimeError: Cannot find scrapy.cfg file".
I have already installed scrapy before, how can i solve this bug?

**Comment by CHerm0** [comment]
Hi:
I have same question, did you solve?

**Comment by ziyou8** [comment]
Maybe you need to run `scrapy startproject projectname` create a project first, then inside the project folder run the `scrapyrt` command.
