### ISSUE TITLE
cannot import name 'log' from 'scrapy' 

### ISSUE THREAD

**Issue by TrinityHC** [scrapinghub/scrapyrt#91]
I saw you merged in the log branch and saw the change on master
but when i pip install and run
it still have this issus
```
from scrapy import signals, log as scrapy_log
builtins.ImportError: cannot import name 'log' from 'scrapy' (/Users/hao.chen/Envs/spiders/lib/python3.7/site-packages/scrapy/__init__.py)
```

how to install the newest version on pip

**Comment by pawelmhm** [comment]
I'm going to make a release soon.

**Comment by pawelmhm** [comment]
there is new version relased now to pypi, so please check now

**Comment by hchen-markettrack** [comment]
@pawelmhm Thanks
