### ISSUE TITLE
Scrapyrt doesn't complete job

### ISSUE THREAD

**Issue by voxum** [scrapinghub/scrapyrt#92]
I have a spider that yields new requests depending on how many results are displayed on my target site. My issue is scrapyrt stops after 7 requests, but running my spider through scrapy crawl or python "Script name" gives me the expected results. Anyone experience anything like this ?

**Comment by pawelmhm** [comment]
can you provide some example code to reproduce your issue @voxum? What do you mean by "scrapryt stops after 7 requests?" does it mean it crashes? Or it means spider only makes 7 requests and returns response? How many requests do you expect?

Without all these details it is impossible to know what is wrong or if anything is actually wrong with Scrapyrt

**Comment by voxum** [comment]
Thanks for the response, I've figured out my issue and it turned out to be not related to scrapyrt.
