### ISSUE TITLE
Can't get ScrapyRT to work on Azure Ubuntu 18.04 VM

### ISSUE THREAD

**Issue by jordankendall86** [scrapinghub/scrapyrt#96]
I have successfully implemented Scrapy on my Azure VM, but I can't seem to get the ScrapyRT to work.  I used the example at this [link](https://medium.com/@mottet.dev/scrapy-and-scrapyrt-how-to-create-your-own-api-from-almost-any-website-ecfb0058ad64).  I have set the 9080 port open to all traffic in/out and I still keep getting "This site can’t be reached" and "[my public IP] refused to connect."  I am using the url:  http://myPublicIP:9080/crawl.json?start_requests=true&spider_name=coin  My guess is I have something wrong in Azure VM settings, but I have checked multiple times to make sure the settings are right.  Any suggestions?

**Comment by jordankendall86** [comment]
I have made repeated attempts to open port 9080.  I used nmap as you
suggested to monitor my attempts and I still get the following:

[image: image.png]

I have setup ufw and it says port 9080 is open:

[image: image.png]

You can also see in the prior screenshot I added a profile for ScrapyRT and
that did not help.

I have ran commands like:

[image: image.png]

Nothing changes the results of nmap.  I have also tried to setup the server
to listen to port 9080, but have only been able to get it to work with the
following command:

[image: image.png]

but it just times out.  I assume running scrapyrt in the scrapy project
folder accomplishes something similar, but not sure (see below).

[image: image.png]

I feel as though I have tried a hundred things and I have still made no
progress.  Did anything I try above help?  Am I going in the right
direction?

Jordan Kendall

**Comment by jordankendall86** [comment]
So here is an update.  I ran the following in the terminal:
![image](https://user-images.githubusercontent.com/49451512/66789641-5aaddd80-eea1-11e9-879f-62ac569f37c8.png)

I also ran this in the terminal:
![image](https://user-images.githubusercontent.com/49451512/66789673-7e712380-eea1-11e9-882b-6663562e289c.png)

So I was able to get the port open, but now I get the following in the terminal when I try to access it using http://publicIP:8080/crawl.json?start_requests=true&spider_name=coin
![image](https://user-images.githubusercontent.com/49451512/66789743-c8f2a000-eea1-11e9-8576-793ce90b2b29.png)

Then it hangs and times out.  That is some progress.  Hopefully those details can help someone understand my problem a little better and provide more direction on how to get this to work.

**Comment by jordankendall86** [comment]
I have made repeated attempts to open port 9080.  I used nmap as you
suggested to monitor my attempts and I still get the following:
![image](https://user-images.githubusercontent.com/49451512/66789821-2edf2780-eea2-11e9-8b6f-b5421603db1d.png)


I have setup ufw and it says port 9080 is open:
![image](https://user-images.githubusercontent.com/49451512/66782706-28918100-ee8b-11e9-8c14-26e5f5f5b91a.png)

You can also see in the prior screenshot I added a profile for ScrapyRT and
that did not help.

I have ran commands like:
![image](https://user-images.githubusercontent.com/49451512/66782726-3941f700-ee8b-11e9-8983-5420812e2d23.png)

Nothing changes the results of nmap.  I have also tried to setup the server
to listen to port 9080, but have only been able to get it to work with the
following command:
![image](https://user-images.githubusercontent.com/49451512/66782750-45c64f80-ee8b-11e9-8cf8-a1437bcbc08a.png)

but it just times out.  I assume running scrapyrt in the scrapy project
folder accomplishes something similar, but not sure (see below).
![image](https://user-images.githubusercontent.com/49451512/66782762-4d85f400-ee8b-11e9-870c-f700e0119b99.png)

So here is an update. I ran the following in the terminal:
![image](https://user-images.githubusercontent.com/49451512/66789641-5aaddd80-eea1-11e9-879f-62ac569f37c8.png)

I also ran this in the terminal:
![image](https://user-images.githubusercontent.com/49451512/66789673-7e712380-eea1-11e9-882b-6663562e289c.png)

So I was able to get the port open, but now I get the following in the terminal when I try to access it using http://publicIP:8080/crawl.json?start_requests=true&spider_name=coin
![image](https://user-images.githubusercontent.com/49451512/66789743-c8f2a000-eea1-11e9-8576-793ce90b2b29.png)

Then it hangs and times out. That is some progress. Hopefully those details can help someone understand my problem a little better and provide more direction on how to get this to work.  I feel as though I have tried a hundred things. Did anything I try above help?  Am I going in the right
direction?

**Comment by BuSSioR** [comment]
Wild guess, check if this port is open in your azure server settings. When you nmap this IP state of 9080 port should be open. https://docs.microsoft.com/en-au/azure/virtual-machines/windows/nsg-quickstart-portal This might be helpful.

**Comment by jordankendall86** [comment]
I have checked my Azure server network settings and all ports I have tested, 9080 and 8080, are open to all sources of traffic.  See screenshot below:
![image](https://user-images.githubusercontent.com/49451512/66855728-a6f82c80-ef38-11e9-8602-2edda76a6187.png)

The screenshots in my previous comment clearly show that I got the ports to open, but now the problem is the API call hangs within the browser and does not fully execute the scrape.  I also provided in the previous comment a screenshot showing that progress within the terminal.  Like I said before, the scrape works locally, I just cannot get it to work over ScrapyRT.

I forgot to mention earlier that I tried the following commands:
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 9080 -j ACCEPT
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT
sudo /sbin/iptables-save

This seemed to help, but I thought ufw was layered over iptables.

I am curious to know if I am not supposed to use the "nc" command to open a port, because when I do I cannot use the command "scrapyrt -p 9080"

**Comment by jordankendall86** [comment]
So I got it to work.  Here is what I ran in the terminal:
![image](https://user-images.githubusercontent.com/49451512/66901366-6e496900-efb3-11e9-8173-57ef77e2b6b5.png)
As you can see I had to use "-i 0.0.0.0" otherwise the server would default to "127.0.0.1" which is localhost.
And here is proof of port open:
![image](https://user-images.githubusercontent.com/49451512/66901711-15c69b80-efb4-11e9-8440-cb1817cb3574.png)
I thought I had tried the "-i" option before, but maybe as I was stumbling through each troubleshoot I resolved something that finally made using that option work.  Hopefully this helps someone.
